spring:
  security:
    user:
      name: user
      password: password
  application:
    name: ericsson-task
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
      FAIL_ON_IGNORED_PROPERTIES: true
application:
  title: Harry Kart
  description: <h3> Simple app for Harry Kart game </h3>
  version: 0.0.1
  race:
    number-of-winners: 3
    track-length: 1000

